/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip;

public interface exampleConstants {
  public final static int OPAL_C_API_VERSION = exampleJNI.OPAL_C_API_VERSION_get();
  public final static String OPAL_INITIALISE_FUNCTION = exampleJNI.OPAL_INITIALISE_FUNCTION_get();
  public final static String OPAL_SHUTDOWN_FUNCTION = exampleJNI.OPAL_SHUTDOWN_FUNCTION_get();
  public final static String OPAL_GET_MESSAGE_FUNCTION = exampleJNI.OPAL_GET_MESSAGE_FUNCTION_get();
  public final static String OPAL_SEND_MESSAGE_FUNCTION = exampleJNI.OPAL_SEND_MESSAGE_FUNCTION_get();
  public final static String OPAL_FREE_MESSAGE_FUNCTION = exampleJNI.OPAL_FREE_MESSAGE_FUNCTION_get();
  public final static String OPAL_PREFIX_H323 = exampleJNI.OPAL_PREFIX_H323_get();
  public final static String OPAL_PREFIX_SIP = exampleJNI.OPAL_PREFIX_SIP_get();
  public final static String OPAL_PREFIX_IAX2 = exampleJNI.OPAL_PREFIX_IAX2_get();
  public final static String OPAL_PREFIX_PCSS = exampleJNI.OPAL_PREFIX_PCSS_get();
  public final static String OPAL_PREFIX_LOCAL = exampleJNI.OPAL_PREFIX_LOCAL_get();
  public final static String OPAL_PREFIX_POTS = exampleJNI.OPAL_PREFIX_POTS_get();
  public final static String OPAL_PREFIX_PSTN = exampleJNI.OPAL_PREFIX_PSTN_get();
  public final static String OPAL_PREFIX_IVR = exampleJNI.OPAL_PREFIX_IVR_get();
  public final static String OPAL_PREFIX_ALL = exampleJNI.OPAL_PREFIX_ALL_get();
}
