/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip;

public class example implements exampleConstants {
  public static SWIGTYPE_p_OpalHandleStruct OpalInitialise(long[] INOUT, String INPUT) {
    long cPtr = exampleJNI.OpalInitialise(INOUT, INPUT);
    return (cPtr == 0) ? null : new SWIGTYPE_p_OpalHandleStruct(cPtr, false);
  }

  public static SWIGTYPE_p_OpalMessage OpalSendMessage(SWIGTYPE_p_OpalHandleStruct arg0, SWIGTYPE_p_OpalMessage arg1) {
    long cPtr = exampleJNI.OpalSendMessage(SWIGTYPE_p_OpalHandleStruct.getCPtr(arg0), SWIGTYPE_p_OpalMessage.getCPtr(arg1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_OpalMessage(cPtr, false);
  }

  public static void OpalShutDown(SWIGTYPE_p_OpalHandleStruct opal) {
    exampleJNI.OpalShutDown(SWIGTYPE_p_OpalHandleStruct.getCPtr(opal));
  }

  public static SWIGTYPE_p_OpalMessage OpalGetMessage(SWIGTYPE_p_OpalHandleStruct opal, long timeout) {
    long cPtr = exampleJNI.OpalGetMessage(SWIGTYPE_p_OpalHandleStruct.getCPtr(opal), timeout);
    return (cPtr == 0) ? null : new SWIGTYPE_p_OpalMessage(cPtr, false);
  }

  public static void OpalFreeMessage(SWIGTYPE_p_OpalMessage message) {
    exampleJNI.OpalFreeMessage(SWIGTYPE_p_OpalMessage.getCPtr(message));
  }

}
