/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip;

public class OpalStatusLineAppearance {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OpalStatusLineAppearance(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalStatusLineAppearance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalStatusLineAppearance(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_line(String value) {
    OPALJNI.OpalStatusLineAppearance_m_line_set(swigCPtr, this, value);
  }

  public String getM_line() {
    return OPALJNI.OpalStatusLineAppearance_m_line_get(swigCPtr, this);
  }

  public void setM_state(OpalLineAppearanceStates value) {
    OPALJNI.OpalStatusLineAppearance_m_state_set(swigCPtr, this, value.swigValue());
  }

  public OpalLineAppearanceStates getM_state() {
    return OpalLineAppearanceStates.swigToEnum(OPALJNI.OpalStatusLineAppearance_m_state_get(swigCPtr, this));
  }

  public void setM_appearance(int value) {
    OPALJNI.OpalStatusLineAppearance_m_appearance_set(swigCPtr, this, value);
  }

  public int getM_appearance() {
    return OPALJNI.OpalStatusLineAppearance_m_appearance_get(swigCPtr, this);
  }

  public void setM_callId(String value) {
    OPALJNI.OpalStatusLineAppearance_m_callId_set(swigCPtr, this, value);
  }

  public String getM_callId() {
    return OPALJNI.OpalStatusLineAppearance_m_callId_get(swigCPtr, this);
  }

  public void setM_partyA(String value) {
    OPALJNI.OpalStatusLineAppearance_m_partyA_set(swigCPtr, this, value);
  }

  public String getM_partyA() {
    return OPALJNI.OpalStatusLineAppearance_m_partyA_get(swigCPtr, this);
  }

  public void setM_partyB(String value) {
    OPALJNI.OpalStatusLineAppearance_m_partyB_set(swigCPtr, this, value);
  }

  public String getM_partyB() {
    return OPALJNI.OpalStatusLineAppearance_m_partyB_get(swigCPtr, this);
  }

  public OpalStatusLineAppearance() {
    this(OPALJNI.new_OpalStatusLineAppearance(), true);
  }

}
