/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip;

public class OpalStatusIncomingCall {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OpalStatusIncomingCall(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalStatusIncomingCall obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalStatusIncomingCall(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_callToken(String value) {
    OPALJNI.OpalStatusIncomingCall_m_callToken_set(swigCPtr, this, value);
  }

  public String getM_callToken() {
    return OPALJNI.OpalStatusIncomingCall_m_callToken_get(swigCPtr, this);
  }

  public void setM_localAddress(String value) {
    OPALJNI.OpalStatusIncomingCall_m_localAddress_set(swigCPtr, this, value);
  }

  public String getM_localAddress() {
    return OPALJNI.OpalStatusIncomingCall_m_localAddress_get(swigCPtr, this);
  }

  public void setM_remoteAddress(String value) {
    OPALJNI.OpalStatusIncomingCall_m_remoteAddress_set(swigCPtr, this, value);
  }

  public String getM_remoteAddress() {
    return OPALJNI.OpalStatusIncomingCall_m_remoteAddress_get(swigCPtr, this);
  }

  public void setM_remotePartyNumber(String value) {
    OPALJNI.OpalStatusIncomingCall_m_remotePartyNumber_set(swigCPtr, this, value);
  }

  public String getM_remotePartyNumber() {
    return OPALJNI.OpalStatusIncomingCall_m_remotePartyNumber_get(swigCPtr, this);
  }

  public void setM_remoteDisplayName(String value) {
    OPALJNI.OpalStatusIncomingCall_m_remoteDisplayName_set(swigCPtr, this, value);
  }

  public String getM_remoteDisplayName() {
    return OPALJNI.OpalStatusIncomingCall_m_remoteDisplayName_get(swigCPtr, this);
  }

  public void setM_calledAddress(String value) {
    OPALJNI.OpalStatusIncomingCall_m_calledAddress_set(swigCPtr, this, value);
  }

  public String getM_calledAddress() {
    return OPALJNI.OpalStatusIncomingCall_m_calledAddress_get(swigCPtr, this);
  }

  public void setM_calledPartyNumber(String value) {
    OPALJNI.OpalStatusIncomingCall_m_calledPartyNumber_set(swigCPtr, this, value);
  }

  public String getM_calledPartyNumber() {
    return OPALJNI.OpalStatusIncomingCall_m_calledPartyNumber_get(swigCPtr, this);
  }

  public void setM_product(OpalProductDescription value) {
    OPALJNI.OpalStatusIncomingCall_m_product_set(swigCPtr, this, OpalProductDescription.getCPtr(value), value);
  }

  public OpalProductDescription getM_product() {
    long cPtr = OPALJNI.OpalStatusIncomingCall_m_product_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OpalProductDescription(cPtr, false);
  }

  public void setM_alertingType(String value) {
    OPALJNI.OpalStatusIncomingCall_m_alertingType_set(swigCPtr, this, value);
  }

  public String getM_alertingType() {
    return OPALJNI.OpalStatusIncomingCall_m_alertingType_get(swigCPtr, this);
  }

  public void setM_protocolCallId(String value) {
    OPALJNI.OpalStatusIncomingCall_m_protocolCallId_set(swigCPtr, this, value);
  }

  public String getM_protocolCallId() {
    return OPALJNI.OpalStatusIncomingCall_m_protocolCallId_get(swigCPtr, this);
  }

  public OpalStatusIncomingCall() {
    this(OPALJNI.new_OpalStatusIncomingCall(), true);
  }

}
