/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip;

public final class OpalRegistrationStates {
  public final static OpalRegistrationStates OpalRegisterSuccessful = new OpalRegistrationStates("OpalRegisterSuccessful");
  public final static OpalRegistrationStates OpalRegisterRemoved = new OpalRegistrationStates("OpalRegisterRemoved");
  public final static OpalRegistrationStates OpalRegisterFailed = new OpalRegistrationStates("OpalRegisterFailed");
  public final static OpalRegistrationStates OpalRegisterRetrying = new OpalRegistrationStates("OpalRegisterRetrying");
  public final static OpalRegistrationStates OpalRegisterRestored = new OpalRegistrationStates("OpalRegisterRestored");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OpalRegistrationStates swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OpalRegistrationStates.class + " with value " + swigValue);
  }

  private OpalRegistrationStates(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OpalRegistrationStates(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OpalRegistrationStates(String swigName, OpalRegistrationStates swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OpalRegistrationStates[] swigValues = { OpalRegisterSuccessful, OpalRegisterRemoved, OpalRegisterFailed, OpalRegisterRetrying, OpalRegisterRestored };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

