/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip;

public class OpalStatusCallCleared {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OpalStatusCallCleared(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalStatusCallCleared obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalStatusCallCleared(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_callToken(String value) {
    OPALJNI.OpalStatusCallCleared_m_callToken_set(swigCPtr, this, value);
  }

  public String getM_callToken() {
    return OPALJNI.OpalStatusCallCleared_m_callToken_get(swigCPtr, this);
  }

  public void setM_reason(String value) {
    OPALJNI.OpalStatusCallCleared_m_reason_set(swigCPtr, this, value);
  }

  public String getM_reason() {
    return OPALJNI.OpalStatusCallCleared_m_reason_get(swigCPtr, this);
  }

  public OpalStatusCallCleared() {
    this(OPALJNI.new_OpalStatusCallCleared(), true);
  }

}
