/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip;

public interface OPALConstants {
  public final static int OPAL_C_API_VERSION = OPALJNI.OPAL_C_API_VERSION_get();
  public final static String OPAL_INITIALISE_FUNCTION = OPALJNI.OPAL_INITIALISE_FUNCTION_get();
  public final static String OPAL_SHUTDOWN_FUNCTION = OPALJNI.OPAL_SHUTDOWN_FUNCTION_get();
  public final static String OPAL_GET_MESSAGE_FUNCTION = OPALJNI.OPAL_GET_MESSAGE_FUNCTION_get();
  public final static String OPAL_SEND_MESSAGE_FUNCTION = OPALJNI.OPAL_SEND_MESSAGE_FUNCTION_get();
  public final static String OPAL_FREE_MESSAGE_FUNCTION = OPALJNI.OPAL_FREE_MESSAGE_FUNCTION_get();
  public final static String OPAL_PREFIX_H323 = OPALJNI.OPAL_PREFIX_H323_get();
  public final static String OPAL_PREFIX_SIP = OPALJNI.OPAL_PREFIX_SIP_get();
  public final static String OPAL_PREFIX_IAX2 = OPALJNI.OPAL_PREFIX_IAX2_get();
  public final static String OPAL_PREFIX_PCSS = OPALJNI.OPAL_PREFIX_PCSS_get();
  public final static String OPAL_PREFIX_LOCAL = OPALJNI.OPAL_PREFIX_LOCAL_get();
  public final static String OPAL_PREFIX_POTS = OPALJNI.OPAL_PREFIX_POTS_get();
  public final static String OPAL_PREFIX_PSTN = OPALJNI.OPAL_PREFIX_PSTN_get();
  public final static String OPAL_PREFIX_IVR = OPALJNI.OPAL_PREFIX_IVR_get();
  public final static String OPAL_PREFIX_ALL = OPALJNI.OPAL_PREFIX_ALL_get();
  public final static String OPAL_MWI_EVENT_PACKAGE = OPALJNI.OPAL_MWI_EVENT_PACKAGE_get();
  public final static String OPAL_LINE_APPEARANCE_EVENT_PACKAGE = OPALJNI.OPAL_LINE_APPEARANCE_EVENT_PACKAGE_get();
}
