/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip;

public class OpalParamRecording {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OpalParamRecording(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalParamRecording obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalParamRecording(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_callToken(String value) {
    OPALJNI.OpalParamRecording_m_callToken_set(swigCPtr, this, value);
  }

  public String getM_callToken() {
    return OPALJNI.OpalParamRecording_m_callToken_get(swigCPtr, this);
  }

  public void setM_file(String value) {
    OPALJNI.OpalParamRecording_m_file_set(swigCPtr, this, value);
  }

  public String getM_file() {
    return OPALJNI.OpalParamRecording_m_file_get(swigCPtr, this);
  }

  public void setM_channels(long value) {
    OPALJNI.OpalParamRecording_m_channels_set(swigCPtr, this, value);
  }

  public long getM_channels() {
    return OPALJNI.OpalParamRecording_m_channels_get(swigCPtr, this);
  }

  public void setM_audioFormat(String value) {
    OPALJNI.OpalParamRecording_m_audioFormat_set(swigCPtr, this, value);
  }

  public String getM_audioFormat() {
    return OPALJNI.OpalParamRecording_m_audioFormat_get(swigCPtr, this);
  }

  public void setM_videoFormat(String value) {
    OPALJNI.OpalParamRecording_m_videoFormat_set(swigCPtr, this, value);
  }

  public String getM_videoFormat() {
    return OPALJNI.OpalParamRecording_m_videoFormat_get(swigCPtr, this);
  }

  public void setM_videoWidth(long value) {
    OPALJNI.OpalParamRecording_m_videoWidth_set(swigCPtr, this, value);
  }

  public long getM_videoWidth() {
    return OPALJNI.OpalParamRecording_m_videoWidth_get(swigCPtr, this);
  }

  public void setM_videoHeight(long value) {
    OPALJNI.OpalParamRecording_m_videoHeight_set(swigCPtr, this, value);
  }

  public long getM_videoHeight() {
    return OPALJNI.OpalParamRecording_m_videoHeight_get(swigCPtr, this);
  }

  public void setM_videoRate(long value) {
    OPALJNI.OpalParamRecording_m_videoRate_set(swigCPtr, this, value);
  }

  public long getM_videoRate() {
    return OPALJNI.OpalParamRecording_m_videoRate_get(swigCPtr, this);
  }

  public void setM_videoMixing(OpalVideoRecordMixMode value) {
    OPALJNI.OpalParamRecording_m_videoMixing_set(swigCPtr, this, value.swigValue());
  }

  public OpalVideoRecordMixMode getM_videoMixing() {
    return OpalVideoRecordMixMode.swigToEnum(OPALJNI.OpalParamRecording_m_videoMixing_get(swigCPtr, this));
  }

  public OpalParamRecording() {
    this(OPALJNI.new_OpalParamRecording(), true);
  }

}
