//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by YYSpriteX-2.rc
//
#define IDS_YYSPRITEX2                  1
#define IDS_YYSPRITEX2_PPG              2
#define IDD_ABOUTBOX_YYSPRITEX2         3
#define IDB_YYSPRITEX2                  4
#define IDI_ABOUTDLL                    5
#define IDOK2                           6
#define IDCANCEL2                       7
#define IDD_CATCHSCREEN_DIALOG          102
#define IDR_HTML_OPTIONSEXDLG           103
#define IDD_PROPPAGE_DEVICES            107
#define IDD_PROPPAGE_APPLICATION        108
#define IDC_CURSOR2                     109
#define IDR_MAINFRAME                   110
#define IDB_BITMAP_CAMERA               125
#define IDC_CURSOR4                     126
#define IDC_CURSOR1                     127
#define IDD_DIALOG_INCOMING             128
#define IDD_DIALOG_REMOTE               129
#define IDB_BITMAP_R                    130
#define IDB_BITMAP_AUDIO                131
#define IDB_BITMAP_AUDIO2               132
#define IDC_CURSOR3                     133
#define IDB_BITMAP_CLOSE2               134
#define IDC_CURSOR5                     135
#define IDC_CURSOR6                     136
#define IDB_BITMAP_CAMERA2              137
#define IDD_PROPPAGE_QOS                138
#define IDB_BITMAP_CLOSE                139
#define IDD_DIALOG_VIDEO_CENTER         140
#define IDB_BITMAP_MINIMIZE2            141
#define IDB_BITMAP_MINIMIZE             142
#define IDD_PROPPAGE_H323               143
#define IDB_BITMAP_INCOMING             144
#define IDB_BITMAPACCEPT                145
#define IDD_PROPPAGE_VIDEOCODEC         146
#define IDB_BITMAPREJECT                147
#define IDB_BITMAP_MENU2                148
#define IDD_PROPPAGE_AUDIOCODEC         149
#define IDR_MENU_VIDEO_CTRL             150
#define IDR_MENU_VIDEO_CTRL_EN          151
#define IDB_BITMAP_MENU                 152
#define IDS_YYSPRITEX2_PPG_CAPTION      199
#define IDD_PROPPAGE_YYSPRITEX2         200
#define IDC_STATIC_INCOING              201
#define IDR_WAVE_RINGOUT                202
#define IDC_STATIC_TITLE                203
#define IDR_WAVE_BLIP                   204
#define IDC_STATIC_VIDEO_TITLE          209
#define IDC_TRANSPORT                   210
#define IDD_DIALOG_OPTIONS              211
#define IDB_BITMAP_RECORDING_2          212
#define IDB_BITMAP_RECORDING_1          213
#define IDR_WAVE_RING                   214
#define IDR_WAVE_CALL                   215
#define IDC_EDIT2                       215
#define IDR_WAVE_MSG                    216
#define IDD_DIALOG_VIDEO_CHILD          217
#define IDD_DIALOG_VIDEO_PANEL          218
#define IDR_MENU1                       219
#define IDB_BITMAPACCEPT1               220
#define IDD_DIALOG2                     221
#define IDR_MENU_VIDEO_LAYOUT_CTRL      222
#define IDR_MENU_VIDEO_LAYOUT_CTRL_EN   230
#define IDC_EDIT_USER                   1000
#define IDC_EDIT1                       1001
#define IDC_LIST_RINGTONES              1002
#define IDC_BUTTON_IMPORT               1004
#define IDC_BUTTON_PLAY                 1006
#define IDC_COMBO_MICROPHONE            1007
#define IDC_BUTTON_STOP                 1008
#define IDC_COMBO_SPEAKER               1009
#define IDC_BUTTON_ACTIVE               1010
#define IDC_CHECK_SENDVIDEO             1014
#define IDC_CHECK_SENDAUDIO             1015
#define IDC_CHECK_CLOSE                 1016
#define IDC_CHECK_MINIMIZE              1017
#define IDC_BUTTON_ACCEPT               1018
#define IDC_CHECK_RECORDING             1018
#define IDC_BUTTON_REJECT               1019
#define IDC_COMBO_MICROPHONE2           1020
#define IDC_STATIC_STATE                1021
#define IDC_RADIO_AUDIO_NONE            1022
#define IDC_STATIC_STATE2               1022
#define IDC_STATIC_STATE_DURATION       1022
#define IDC_CHECK_UAC                   1023
#define IDC_EDIT_DISPAY                 1024
#define IDC_RADIO_AUDIO_USE             1025
#define IDC_LIST1                       1026
#define IDC_RADIO_AUDIO_NONE2           1027
#define IDC_CHECK_UAGC                  1028
#define IDC_LIST2                       1029
#define IDC_EDIT_PASSWORD               1030
#define IDC_RADIO_AUDIO_USE2            1031
#define IDC_BUTTON_SIP_APPLY            1031
#define IDC_EDIT_AUTH                   1032
#define Description                     1033
#define IDC_EDIT_DOMAIN                 1034
#define IDC_CHECK_UNR                   1035
#define IDC_EDIT_DOMAINPROXCY           1036
#define IDC_EDIT_DESCRIPTION            1037
#define IDC_CHECK_MENU                  1037
#define IDC_COMBO_RING                  1038
#define IDC_SLIDER_VOLUME               1039
#define IDC_COMBO_CAMERA                1040
#define IDC_CHECK_DISABLE_HARDWARE      1041
#define IDC_BUTTON2                     1042
#define IDC_BUTTON3                     1043
#define IDC_CHECK_SENDAUDIO2            1050
#define IDD_PROPPAGE_SIP                1407
#define IDR_TRAY                        2100
#define IDD_HELP                        2101
#define ID_CONN_CTLESC                  2102
#define IDR_TRAYMENU                    2103
#define ID_CONN_CTLDOWN                 2104
#define IDR_MENU_VIDEO_LAYOUT_CTRL1     2104
#define IDR_MENU_VIDEO_LAYOUT_POP       2104
#define IDC_DOTCURSOR                   2105
#define IDB_VNCBITMAP                   2106
#define ID_CONN_CTLALTDEL               2108
#define IDD_APP_ABOUT                   2109
#define ID_FULLSCREEN                   2110
#define ID_REQUEST_REFRESH              2111
#define IDD_SESSION_DLG                 2135
#define IDD_SERVINFO_DLG                2137
#define IDD_AUTH_DIALOG                 2138
#define IDD_LOGIN_AUTH_DIALOG           2139
#define IDD_OPTIONDIALOG                2151
#define IDT_EMULATE3BUTTONSTIMER        2152
#define ID_CONN_SAVE_AS                 2153
#define IDC_NOCURSOR                    2153
#define IDR_VERSION2                    2154
#define IDB_BITMAP1                     2158
#define ID_TOOLBAR                      2159
#define ID_DISCONNECT                   2160
#define IDB_BITMAP_CAPTURE              2161
#define IDD_DIALOG1                     2163
#define IDD_FTBROWSE_DLG                2217
#define IDD_FILETRANSFER_DLG            2219
#define IDD_FILETRANSFER_ABOUT          2233
#define IDI_FILERELOAD                  2241
#define IDC_SMALLDOT                    2244
#define IDD_CONNECTING_DIALOG           2245
#define ID_CONN_ABOUT                   2303
#define ID_CONN_CTLUP                   2305
#define ID_CONN_ALTDOWN                 2306
#define IDD_GENERAL_OPTION              2307
#define ID_CONN_ALTUP                   2308
#define IDD_PARENT                      2309
#define IDB_VNC32                       2318
#define IDT_TRAYTIMER                   2319
#define IDC_HOSTNAME_EDIT               21000
#define IDC_DPYNUM_EDIT                 21001
#define IDC_BELLDEICONIFY               21002
#define IDC_SERVINFO_EDIT               21003
#define IDC_VIEWONLY                    21005
#define IDC_LOGIN_EDIT                  21008
#define IDC_PASSWD_EDIT                 21009
#define IDC_TAB                         21010
#define IDC_OPTIONBUTTON                21012
#define IDC_8BITCHECK                   21013
#define IDC_RAWRADIO                    21018
#define IDC_CRECTRADIO                  21019
#define IDC_RRERADIO                    21020
#define IDC_RBSRADIO                    21021
#define IDC_CORRERADIO                  21022
#define IDC_HEXTILERADIO                21023
#define IDC_ZLIBRADIO                   21024
#define IDC_TIGHTRADIO                  21025
#define IDC_ZLIBHEXRADIO                21026
#define IDC_EMULATECHECK                21027
#define IDC_FULLSCREEN                  21028
#define IDC_DISABLECLIPBOARD            21029
#define IDC_SCALING                     21030
#define IDC_SCALE_NUM                   21031
#define IDC_SCALE_DEN                   21032
#define IDC_CSHAPE_DISABLE_RADIO        21033
#define IDC_QUALITYLEVEL                21034
#define IDC_COMPRESSLEVEL               21035
#define IDC_CSHAPE_ENABLE_RADIO         21036
#define IDC_CSHAPE_IGNORE_RADIO         21037
#define IDC_LOC_NET_RADIO               21041
#define IDC_MODEM_RADIO                 21042
#define IDC_CUSTOM_RADIO                21043
#define IDC_OK                          21044
#define IDC_LIST_MODE                   21047
#define IDC_CHECK_MESSAGE               21048
#define IDC_CHECK_TOOLBAR               21049
#define IDC_EDIT_AMOUNT_LIST            21050
#define IDC_BUTTON_CLEAR_LIST           21051
#define IDC_CHECK_LOG_FILE              21052
#define IDC_EDIT_LOG_FILE               21053
#define IDC_FTBROWSETREE                21054
#define IDC_FTBROWSECANCEL              21055
#define IDC_FTBROWSEOK                  21056
#define IDC_EDIT_LOG_LEVEL              21057
#define IDC_SHARED                      21059
#define IDC_SPIN1                       21060
#define IDC_SPIN2                       21061
#define IDC_SPIN3                       21062
#define IDC_SPIN4                       21063
#define IDC_ENCODING                    21065
#define IDC_SCALE_EDIT                  21069
#define IDC_DOTCURSOR_RADIO             21070
#define IDC_NOCURSOR_RADIO              21071
#define IDC_NORMALCURSOR_RADIO          21072
#define IDC_EDIT_HELP                   21076
#define IDC_STATIC_LEVEL                21078
#define IDC_STATIC_QUALITY              21079
#define IDC_UPLOAD                      21080
#define IDC_DOWNLOAD                    21081
#define IDC_CLIENTPATH                  21082
#define IDC_CLIENTBROWSE_BUT            21083
#define IDC_SERVERPATH                  21084
#define IDC_SERVERBROWSE_BUT            21085
#define IDC_FTCLIENTLIST                21086
#define IDC_FTSERVERLIST                21087
#define IDC_FTABOUT                     21088
#define IDC_FTCANCEL                    21089
#define IDC_EXIT                        21090
#define IDC_FTPROGRESS                  21091
#define IDC_FTBROWSEEDIT                21092
#define IDC_LOAD                        21093
#define IDC_SERVERRELOAD                21094
#define IDC_CONN_PROF                   21095
#define IDC_STATIC_TEXT_LEVEL           21096
#define IDC_STATIC_FAST                 21097
#define IDC_STATIC_BEST                 21098
#define IDC_STATIC_TEXT_QUALITY         21099
#define IDC_STATIC_QBEST                21100
#define IDC_STATIC_POOR                 21101
#define IDC_STATIC_ENCODING             21102
#define IDC_STATIC_SCALE                21103
#define IDC_STATIC_P                    21104
#define IDC_STATIC_SERVER               21105
#define IDC_STATIC_LIST                 21106
#define IDC_STATIC_LOG_LEVEL            21108
#define IDC_STATIC_PORT                 21109
#define IDC_STATIC_FORMAT               21110
#define IDC_STATIC_RESTRICTIONS         21111
#define IDC_STATIC_DISPLAY              21112
#define IDC_STATIC_MOUSE                21113
#define IDC_STATIC_MCURSOR              21114
#define IDC_STATIC_IOPTIONS             21115
#define IDC_STATIC_LOGGING              21116
#define IDC_STATIC_LCURSOR              21117
#define IDC_STATIC_LMODE                21118
#define IDC_STATIC_PICTURE              21119
#define IDC_FTCOPY                      21120
#define IDC_SMALLDOTCURSOR_RADIO        21121
#define IDC_VNCHOST                     21124
#define IDC_CONNECTING_STATIC           21125
#define IDC_STATUS_STATIC               21126
#define IDC_LOCAL_COMP_LABEL            21127
#define IDC_TVNC_SERV_LABEL             21128
#define IDC_FTSTATUS                    21130
#define IDC_LISTEN_PORT                 21132
#define IDC_SERVERUP                    21134
#define IDC_BUTTON4                     21135
#define IDC_CLIENTRELOAD                21136
#define IDC_BUTTON5                     21137
#define IDC_CLIENTUP                    21138
#define IDC_LOG_BROWSE                  21139
#define IDC_BUILDTIME                   21140
#define IDC_STATIC_URL                  21141
#define IDC_STATIC_VERSION              21143
#define IDC_STATIC_COPYRIGHTS           21144
#define IDC_STATIC_BASEDON              21145
#define IDC_STATIC_LOGO                 21146
#define IDC_STATIC_HOST                 21147
#define IDC_STATIC_LOGIN                21148
#define IDC_STATIC_PASSWD               21149
#define ID_SESSION_SET_CRECT            23274
#define IDC_ALLOW_COMPRESSLEVEL         23275
#define IDC_ALLOW_JPEG                  23276
#define ID_SESSION_SWAPMOUSE            23278
#define IDD_FILETRANSFER                24001
#define IDS_HELP                        24002
#define ID_NEWCONN                      24003
#define ID_SHOWWINDOW                   24004
#define ID_CLOSEDAEMON                  24005
#define ID_VIDEORATE_64K                32774
#define ID_VIDEORATE_128K               32775
#define ID_VIDEORATE_256K               32776
#define ID_VIDEORATE_384K               32777
#define ID_VIDEORATE_512K               32778
#define ID_VIEOLAYOUT_2X2               32778
#define ID_VIDEORATE_1024K              32779
#define ID_VIDEORATE_2048K              32780
#define ID_VIDEOFRAME_5                 32781
#define ID_VIDEOFRAME_10                32782
#define ID_VIDEOFRAME_15                32783
#define ID_VIEOLAYOUT_                  32783
#define ID_VIDEOFRAME_25                32784
#define ID_VIDEOFRAME_30                32785
#define ID_VIDEOFRAME_60                32786
#define ID_OPTIONS                      32787
#define ID__MINIMIZE                    32788
#define ID_SCREEN_AEAR                  32789
#define ID_ORIGINAL_SIZE                32790
#define ID__MAXIMIZE                    32791
#define ID__64                          32793
#define ID_VIEOLAYOUT_32796             32796
#define ID_Menu_Layout_normal           32811
#define ID_VIEOLAYOUT_32812             32812
#define ID_VIEOLAYOUT_32813             32813
#define ID_VIEOLAYOUT_32814             32814
#define ID_VIEOLAYOUT_TAKEPIC           32815
#define ID_VIEOLAYOUT_CLOSEAUDIO        32816
#define ID_VIEOLAYOUT_CLOSECAMERA       32817
#define ID_VIEOLAYOUT_COPYID            32818
#define ID_VIEOLAYOUT_COPYALIAS         32819
#define ID_VIEOLAYOUT_USERINFO          32820
#define ID__2                           36001
#define ID__4                           36002
#define ID__6                           36003
#define ID__9                           36004
#define ID__12                          36005
#define ID__16                          36006
#define ID__32                          36007
#define ID__0                           36008
#define ID_4_3                          36009
#define ID_5_4                          36010
#define ID_16_9                         36011
#define ID_1_1                          36012
#define ID_VIEOLAYOUT_ADDMCCPANEL       36013
#define ID_VIEOLAYOUT_SWITCH_CC_PANNEL  36014
#define ID_VIEOLAYOUT_HUNGUP            36022
#define ID_Normal                       36023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         216
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
