/*
 * buildopts.h
 *
 * Build options generated by the configure script.
 *
 * Portable Windows Library
 *
 * Copyright (c) 2003 Equivalence Pty. Ltd.
 *
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is Portable Windows Library.
 *
 * The Initial Developer of the Original Code is Equivalence Pty. Ltd.
 *
 * Contributor(s): ______________________________________.
 *
 * $Revision: 21283 $
 * $Author: rjongbloed $
 * $Date: 2008-10-11 07:10:58 +0000 (Sat, 11 Oct 2008) $
 */

#ifndef OPAL_BUILDOPTS_H
#define OPAL_BUILDOPTS_H

#include <ptbuildopts.h>

/////////////////////////////////////////////////
//
// OPAL Version 
//

#define OPAL_MAJOR 3
#define OPAL_MINOR 4
#define OPAL_BUILD 2
#define OPAL_VERSION "3.4.2"

#undef  OPAL_PTLIB_SSL
#undef  OPAL_PTLIB_SSL_AES
#undef  OPAL_PTLIB_ASN
#undef  OPAL_PTLIB_EXPAT
#undef  OPAL_PTLIB_AUDIO
#undef  OPAL_PTLIB_VIDEO
#undef  OPAL_PTLIB_WAVFILE
#undef  OPAL_PTLIB_DTMF
#undef  OPAL_PTLIB_IPV6
#undef  OPAL_PTLIB_DNS
#undef  OPAL_PTLIB_LDAP
#undef  OPAL_PTLIB_VXML
#undef  OPAL_PTLIB_CONFIG_FILE


// If a "configure" did not set these variables above then they get set from PTlib variables

#if defined(P_SSL) && !defined(OPAL_PTLIB_SSL)
  #define  OPAL_PTLIB_SSL P_SSL
#endif
#if defined(P_SSL_AES) && !defined(OPAL_PTLIB_SSL_AES)
  #define  OPAL_PTLIB_SSL_AES P_SSL_AES
#endif
#if defined(P_ASN) && !defined(OPAL_PTLIB_ASN)
  #define  OPAL_PTLIB_ASN P_ASN
#endif
#if defined(P_EXPAT) && !defined(OPAL_PTLIB_EXPAT)
  #define  OPAL_PTLIB_EXPAT P_EXPAT
#endif
#if defined(P_AUDIO) && !defined(OPAL_PTLIB_AUDIO)
  #define  OPAL_PTLIB_AUDIO P_AUDIO
#endif
#if defined(P_VIDEO) && !defined(OPAL_PTLIB_VIDEO)
  #define  OPAL_PTLIB_VIDEO P_VIDEO
#endif
#if defined(P_WAVFILE) && !defined(OPAL_PTLIB_WAVFILE)
  #define  OPAL_PTLIB_WAVFILE P_WAVFILE
#endif
#if defined(P_DTMF) && !defined(OPAL_PTLIB_DTMF)
  #define  OPAL_PTLIB_DTMF P_DTMF
#endif
#if defined(P_HAS_IPV6) && !defined(OPAL_PTLIB_IPV6)
  #define  OPAL_PTLIB_IPV6 P_HAS_IPV6
#endif
#if defined(P_DNS) && !defined(OPAL_PTLIB_DNS)
  #define  OPAL_PTLIB_DNS P_DNS
#endif
#if defined(P_LDAP) && !defined(OPAL_PTLIB_LDAP)
  #define  OPAL_PTLIB_LDAP P_LDAP
#endif
#if defined(P_VXML) && !defined(OPAL_PTLIB_VXML)
  #define  OPAL_PTLIB_VXML P_VXML
#endif
#if defined(P_CONFIG_FILE) && !defined(OPAL_PTLIB_CONFIG_FILE)
  #define  OPAL_PTLIB_CONFIG_FILE P_CONFIG_FILE
#endif

#undef  OPAL_PLUGIN_DIR

/////////////////////////////////////////////////
//
// Protocol support
//
#define OPAL_SIP 1

#undef OPAL_IAX2 
#undef OPAL_H323 
#undef OPAL_LID 
#undef  OPAL_T120DATA

#if OPAL_PTLIB_EXPAT
  #define OPAL_IVR 1
#endif

#if OPAL_H323
  #define OPAL_H224FECC 1
  #define OPAL_H501 1
  
  #define OPAL_H450 1
  #if OPAL_H450
    #define H323_H450   OPAL_H450
  #endif

  #define OPAL_H460 1
  #if OPAL_H460
    #define H323_H460   OPAL_H460
  #endif
#else // OPAL_H323
  #define H323_DISABLE_H225 1
  #define H323_DISABLE_H235 1
  #define H323_DISABLE_H245 1
#endif // OPAL_H323


#if !OPAL_H450
  #define H323_DISABLE_X880 1
  #define H323_DISABLE_H4501 1
  #define H323_DISABLE_H4502 1
  #define H323_DISABLE_H4503 1
  #define H323_DISABLE_H4504 1
  #define H323_DISABLE_H4505 1
  #define H323_DISABLE_H4506 1
  #define H323_DISABLE_H4507 1
  #define H323_DISABLE_H4508 1
  #define H323_DISABLE_H4509 1
  #define H323_DISABLE_H45010 1
  #define H323_DISABLE_H45011 1
#endif


#if !OPAL_T120DATA
  #define H323_DISABLE_GCC 1
  #define H323_DISABLE_MCS 1
#endif // OPAL_T120DATA


#if !OPAL_H501
  #define H323_DISABLE_H501 1
#endif


/////////////////////////////////////////////////
//
// Various options
//

#define OPAL_STATISTICS 1
//#define OPAL_RTP_AGGREGATE   1
#undef GCC_HAS_CLZ


/////////////////////////////////////////////////
//
// Media support
//

#define OPAL_G711PLC 1

#define OPAL_VIDEO 1

#if OPAL_VIDEO
  #define OPAL_RFC4175 1
#endif


//#define OPAL_T38_CAPABILITY 1

#if OPAL_T38_CAPABILITY
  #if OPAL_PTLIB_ASN
    #define OPAL_FAX 1
  #endif
#endif

#if !OPAL_FAX
  #define H323_DISABLE_T38 1
#endif


/////////////////////////////////////////////////
//
// use system Speex

#undef	OPAL_SYSTEM_SPEEX
#undef  OPAL_HAVE_SPEEX_SPEEX_H
#undef  OPAL_SPEEX_FLOAT_NOISE

/////////////////////////////////////////////////
//
// VoiceTronic VPB Support
//

#if OPAL_LID
  #undef HAS_VPB

  #if HAS_VPB
    #if defined(_MSC_VER)
      #pragma include_alias(<vpbapi.h>, <@VPB_DIR@/src/vpbapi.h>)
      #define VPB_LIBRARY "@VPB_DIR@/win32/libvpb/Debug/libvpb.lib"
    #endif
  #endif
#endif


/////////////////////////////////////////////////
//
// libZRTP support
//

#undef HAS_LIBZRTP

#if defined(HAS_LIBZRTP) && !defined(_WIN32_WCE)

  #define OPAL_ZRTP  1

  #if defined(_MSC_VER)

    #ifdef _DEBUG
      #define LIBZRTP_LIBRARY "/Debug/libzrtp.lib"
    #else
      #define LIBZRTP_LIBRARY "/Release/libzrtp.lib"
    #endif

    #pragma comment(lib, LIBZRTP_LIBRARY)

    #pragma include_alias("WINCONFIG/config.h",         "/srtp_win32k/WINCONFIG/config.h")
    #pragma include_alias("WINCONFIG\config.h",         "/srtp_win32k/WINCONFIG/config.h")

    #pragma include_alias(<zrtp.h>,                     </include/zrtp.h>)
    #pragma include_alias(<zrtp_log.h>,                 </include/zrtp_log.h>)
    #pragma include_alias(<zrtp_types.h>,               </include/zrtp_types.h>)   
    #pragma include_alias(<zrtp_crypto.h>,              </include/zrtp_crypto.h>)
    #pragma include_alias(<zrtp_protocol.h>,            </include/zrtp_protocol.h>)
    #pragma include_alias(<zrtp_string.h>,              </include/zrtp_string.h>)
    #pragma include_alias(<zrtp_iface.h>,               </include/zrtp_iface.h>)
    #pragma include_alias(<zrtp_error.h>,               </include/zrtp_error.h>)
    #pragma include_alias(<zrtp_net.h>,                 </include/zrtp_net.h>)
    #pragma include_alias(<zrtp_system.h>,              </include/zrtp_system.h>)
    #pragma include_alias("bn.h",                       "/bnlib/bn.h")
    #pragma include_alias(<bn.h>,                       </bnlib/bn.h>)
    #pragma include_alias("bnsize00.h",                 "/bnlib/bnsize00.h")
    #pragma include_alias(<bnsize00.h>,                 </bnlib/bnsize00.h>)

    #pragma include_alias("aes.h",                      "/bgaes/aes.h")
    #pragma include_alias("sha2.h",                     "/bgaes/sha2.h")

    #pragma include_alias("zrtp_win_config.h",          "/config/zrtp_win_config.h")


    // ZRTP includes SRTP, so include SRTP headers

    #pragma include_alias("srtp.h",              "/srtp_win32k/include/srtp.h")
    #pragma include_alias(<srtp.h>,              </srtp_win32k/include/srtp.h>)
    #pragma include_alias("srtp/srtp.h",         "/srtp_win32k/include/srtp.h")
    #pragma include_alias(<srtp/include/srtp.h>, </srtp_win32k/include/srtp.h>)
    #pragma include_alias("crypto_kernel.h",     "/srtp_win32k/crypto/include/crypto_kernel.h")
    #pragma include_alias("rdbx.h",              "/srtp_win32k/crypto/include/rdbx.h")
    #pragma include_alias("rdb.h",               "/srtp_win32k/crypto/include/rdb.h")
    #pragma include_alias("integers.h",          "/srtp_win32k/crypto/include/integers.h")

    // end of SRTP headers

  #endif
#endif

/////////////////////////////////////////////////
//
// libSRTP support
//

#undef HAS_LIBSRTP

#if HAS_LIBSRTP && !OPAL_ZRTP && !defined(_WIN32_WCE)

  #define OPAL_SRTP  1

  #if defined(_MSC_VER)

    #pragma include_alias("srtp/srtp.h",         "/include/srtp.h")
    #pragma include_alias(<srtp/include/srtp.h>, </include/srtp.h>)
    #pragma include_alias("crypto_kernel.h",     "/crypto/include/crypto_kernel.h")
    #pragma include_alias("rdbx.h",              "/crypto/include/rdbx.h")
    #pragma include_alias("rdb.h",               "/crypto/include/rdb.h")
    #pragma include_alias("integers.h",          "/crypto/include/integers.h")

    #ifdef _DEBUG
      #define LIBSRTP_LIBRARY "/Debug/libsrtp.lib"
    #else
      #define LIBSRTP_LIBRARY "/Release/libsrtp.lib"
    #endif
  #endif
#endif


/////////////////////////////////////////////////
//
// Java JNI support
//

//#define OPAL_JAVA 1
//
//#if OPAL_JAVA
//  #if defined(_MSC_VER)
//    #pragma include_alias(<jni.h>,    <c:/mingw/include/jni.h>)
//    #pragma include_alias("jni_md.h", "c:/mingw/include/win32/jni_md.h")
//  #endif
//#endif


#endif // OPAL_BUILDOPTS_H


// End Of File ///////////////////////////////////////////////////////////////

