//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by YYMcu2.rc
//
#define IDC_MYICON                      2
#define IDD_HELP                        101
#define IDR_TRAY                        101
#define IDD_YYMCU2_DIALOG               102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDR_TRAYMENU                    103
#define IDM_ABOUT                       104
#define IDI_MAINICON                    104
#define IDM_EXIT                        105
#define IDC_DOTCURSOR                   105
#define IDB_VNCBITMAP                   106
#define IDD_GENERAL_OPTION              106
#define IDI_YYMCU2                      107
#define IDD_PARENT                      107
#define IDI_SMALL                       108
#define IDB_VNC32                       108
#define IDC_YYMCU2                      109
#define IDD_APP_ABOUT                   109
#define IDR_MAINFRAME                   128
#define IDD_SESSION_DLG                 135
#define IDD_SERVINFO_DLG                137
#define IDD_LOGIN_AUTH_DIALOG           139
#define IDD_OPTIONDIALOG                151
#define IDC_NOCURSOR                    153
#define IDB_BITMAP1                     158
#define IDD_FTBROWSE_DLG                217
#define IDD_FILETRANSFER_DLG            219
#define IDI_FILEUP                      239
#define IDI_FILERELOAD                  241
#define IDC_SMALLDOT                    244
#define IDD_CONNECTING_DIALOG           245
#define IDC_HOSTNAME_EDIT               1000
#define IDC_BELLDEICONIFY               1002
#define IDC_SERVINFO_EDIT               1003
#define IDC_VIEWONLY                    1005
#define IDC_LOGIN_EDIT                  1008
#define IDC_PASSWD_EDIT                 1009
#define IDC_TAB                         1010
#define IDC_OPTIONBUTTON                1012
#define IDC_8BITCHECK                   1013
#define IDC_EMULATECHECK                1027
#define IDC_FULLSCREEN                  1028
#define IDC_DISABLECLIPBOARD            1029
#define IDC_CSHAPE_DISABLE_RADIO        1033
#define IDC_QUALITYLEVEL                1034
#define IDC_COMPRESSLEVEL               1035
#define IDC_CSHAPE_ENABLE_RADIO         1036
#define IDC_CSHAPE_IGNORE_RADIO         1037
#define IDC_LOC_NET_RADIO               1041
#define IDC_MODEM_RADIO                 1042
#define IDC_CUSTOM_RADIO                1043
#define IDC_OK                          1044
#define IDC_LIST_MODE                   1047
#define IDC_CHECK_MESSAGE               1048
#define IDC_CHECK_TOOLBAR               1049
#define IDC_EDIT_AMOUNT_LIST            1050
#define IDC_BUTTON_CLEAR_LIST           1051
#define IDC_CHECK_LOG_FILE              1052
#define IDC_EDIT_LOG_FILE               1053
#define IDC_FTBROWSETREE                1054
#define IDC_FTBROWSECANCEL              1055
#define IDC_FTBROWSEOK                  1056
#define IDC_EDIT_LOG_LEVEL              1057
#define IDC_SHARED                      1059
#define IDC_SPIN1                       1060
#define IDC_SPIN2                       1061
#define IDC_SPIN3                       1062
#define IDC_ENCODING                    1065
#define IDC_SCALE_EDIT                  1069
#define IDC_DOTCURSOR_RADIO             1070
#define IDC_NOCURSOR_RADIO              1071
#define IDC_NORMALCURSOR_RADIO          1072
#define IDC_EDIT_HELP                   1076
#define IDC_STATIC_LEVEL                1078
#define IDC_STATIC_QUALITY              1079
#define IDC_CLIENTPATH                  1082
#define IDC_CLIENTBROWSE_BUT            1083
#define IDC_SERVERPATH                  1084
#define IDC_SERVERBROWSE_BUT            1085
#define IDC_FTCLIENTLIST                1086
#define IDC_FTSERVERLIST                1087
#define IDC_FTCANCEL                    1089
#define IDC_EXIT                        1090
#define IDC_FTPROGRESS                  1091
#define IDC_FTBROWSEEDIT                1092
#define IDC_LOAD                        1093
#define IDC_SERVERRELOAD                1094
#define IDC_CONN_PROF                   1095
#define IDC_STATIC_TEXT_LEVEL           1096
#define IDC_STATIC_FAST                 1097
#define IDC_STATIC_BEST                 1098
#define IDC_STATIC_TEXT_QUALITY         1099
#define IDC_STATIC_QBEST                1100
#define IDC_STATIC_POOR                 1101
#define IDC_STATIC_ENCODING             1102
#define IDC_STATIC_SCALE                1103
#define IDC_STATIC_P                    1104
#define IDC_STATIC_SERVER               1105
#define IDC_STATIC_LIST                 1106
#define IDC_STATIC_LOG_LEVEL            1108
#define IDC_STATIC_PORT                 1109
#define IDC_STATIC_FORMAT               1110
#define IDC_STATIC_RESTRICTIONS         1111
#define IDC_STATIC_DISPLAY              1112
#define IDC_STATIC_MOUSE                1113
#define IDC_STATIC_MCURSOR              1114
#define IDC_STATIC_IOPTIONS             1115
#define IDC_STATIC_LOGGING              1116
#define IDC_STATIC_LCURSOR              1117
#define IDC_STATIC_LMODE                1118
#define IDC_STATIC_PICTURE              1119
#define IDC_FTCOPY                      1120
#define IDC_SMALLDOTCURSOR_RADIO        1121
#define IDC_VNCHOST                     1124
#define IDC_CONNECTING_STATIC           1125
#define IDC_STATUS_STATIC               1126
#define IDC_LOCAL_COMP_LABEL            1127
#define IDC_TVNC_SERV_LABEL             1128
#define IDC_FTSTATUS                    1130
#define IDC_LISTEN_PORT                 1132
#define IDC_SERVERUP                    1134
#define IDC_CLIENTRELOAD                1136
#define IDC_CLIENTUP                    1138
#define IDC_LOG_BROWSE                  1139
#define IDC_BUILDTIME                   1140
#define IDC_STATIC_URL                  1141
#define IDC_STATIC_VERSION              1143
#define IDC_STATIC_COPYRIGHTS           1144
#define IDC_STATIC_BASEDON              1145
#define IDC_STATIC_LOGO                 1146
#define IDC_STATIC_HOST                 1147
#define IDC_STATIC_LOGIN                1148
#define IDC_STATIC_PASSWD               1149
#define ID_SESSION_SET_CRECT            32777
#define IDC_ALLOW_COMPRESSLEVEL         32778
#define IDC_ALLOW_JPEG                  32779
#define ID_SESSION_SWAPMOUSE            32785
#define ID_CLOSEDAEMON                  40001
#define ID_SHOWWINDOW                   40004
#define ID_NEWCONN                      40006
#define IDS_HELP                        40007
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
